#!/bin/python3

import math
import os
import random
import re
import sys
import collections

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    # Write your code here
    dicionario = {}
    numComb = 0
    for i in ar:
    
        if i in dicionario:
            dicionario[i] += 1
        if i not in dicionario:
            dicionario[i] = 1
    print(dicionario)
    for x in dicionario:
        u = dicionario[x]//2
        numComb += u
    return numComb                           
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
